# Generated by Django 3.2.4 on 2021-07-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_pizza_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='types',
            field=models.CharField(blank=True, choices=[('Contém carne', 'Contém carne'), ('Vegetariana', 'Vegetariana'), ('Vegana', 'Vegana')], max_length=12, null=True),
        ),
    ]
